SkillsFundingAgency/das-platform-automation

- README.md
1. Removed the PlatyPS requirement from the README as per [RFC003](https://github.com/SkillsFundingAgency/das-platform-automation/issues/11). 
2. Minor README revisions.
> Removed PlatyPS Requirement and Minor README Revisions

- GitVersion.yml
- azure-pipelines.yml
> Create GitHub release on master commits

- azure-pipelines.yml
https://docs.microsoft.com/en-us/azure/devops/pipelines/process/stages
> Introduce pipeline stages 

- README.md
Completed the EditorConfig section in the README. Small PR but trying to get all sections of the README finished.
> Completed the EditorConfig Section in the README

- README.md
- azure-pipelines.yml
- Updated PSScriptAnalyzer section
- Minor amendments to Pester section
- Added two URLs to further reading section
- Updated Table of Contents
> Update PSScriptAnalyzer Section and Minor Amendments to README.md

- README.md
Initial draft of the GitHub Releases section. Wanted to get something in for feedback on structure and basic information. Anything specific needs to be added / explained in this section?
> Initial Draft of the GitHub Releases Section.

- Infrastructure-Scripts/Invoke-CdnContentPurge.ps1
- Tests/UT.Invoke-CdnContentPurge.Tests.ps1
- Tests/Unit.Tests.Config.json
- New Script Invoke-CdnContentPurge.ps1 to clear all content from a cdn.
- Associated Unit Tests
- Updated Unit.Tests.Config.json with entries to allow test.
> Added Invoke-CdnContentPurge.ps1 plus Associated Unit Tests +semver: minor

- Infrastructure-Scripts/Add-AppServiceIpException.ps1
- Infrastructure-Scripts/Add-AzSqlIpException.ps1
- Infrastructure-Scripts/Add-CosmosDbIpException.ps1
- Tests/UT.Add-AppServiceIpException.Tests.ps1
- Tests/UT.Add-AzSqlIpException.Tests.ps1
Also creates the access rule names with the user requesting the whitelist by retrieving the value from the environment variables
> Modified Whitelist scripts to update release name +semver: major

- Infrastructure-Scripts/Add-CosmosDbIpException.ps1
- Tests/UT.Add-CosmosDbIpException.Tests.ps1
> Fix CosmosDB Whitelisting

- Infrastructure-Scripts/Set-AzDataFactoryTriggerState.ps1
- Tests/UT.Set-AzDataFactoryTriggerState.Tests.ps1
- Tests/Unit.Tests.Config.json
- Added Set-AzDataFactoryTriggerState.ps1 This module finds all Triggers associated with a DataFactory and Disables them before doing a Resource release.
- Updated shared test config with new DatafactoryName variable.
- Added Unit Tests for the Set-AzDataFactoryTriggerState.ps1  task
> Added  Set-AzDataFactoryTriggerState.ps1  and Associated Scripts +semver: minor

- Infrastructure-Scripts/Set-AzDataFactoryTriggerState.ps1
- Tests/UT.Set-AzDataFactoryTriggerState.Tests.ps1
No Longer throws errors if no Triggers associated with Data factory as this is a Legitimate state. However does output this fact.
Changes unit test to facilitate change in functionality
> Script improvements

- Infrastructure-Scripts/Remove-AzStorageBlobs.ps1
- Tests/UT.Remove-AzStorageBlobs.Tests.ps1
Reversed use of parameter FilesOlderThan and changed to DaysFilesOlderThan
Positive number of days can be used for the DaysFilesOlderThan parameter
> Reversed use of parameter FilesOlderThan and changed to DaysFilesOlderThan +semver: major

- Infrastructure-Scripts/Import-ApimSwaggerApiDefinition.ps1
- Tests/UT.Import-ApimSwaggerApiDefinition.Tests.ps1
Added temporary whitelist of deployment server
Needed when Access Restrictions are on the App Service
> Import-ApimSwaggerApiDefinition: Added temporary whitelist of deployment server +semver: major

- Infrastructure-Scripts/Import-ApimSwaggerApiDefinition.ps1
Removed DNS request to get app service name and added sleep before swagger import
The sleep is needed so the whitelisted IP is in effect.
> Removed DNS request to get app service name and added sleep before swagger import

- Infrastructure-Scripts/Import-ApimSwaggerApiDefinition.ps1
- Tests/UT.Import-ApimSwaggerApiDefinition.Tests.ps1
- Tests/Unit.Tests.Config.json
Edited Import-ApimSwaggerApiDefinition ApiName parameter with ApiVersionSetName
API Name is retrieved from the swagger definition
> Edited Import-ApimSwaggerApiDefinition ApiName parameter with ApiVersionSetName +semver: major

- Infrastructure-Scripts/Import-ApimSwaggerApiDefinition.ps1
- Tests/UT.Import-ApimSwaggerApiDefinition.Tests.ps1
- Changed function Read-IndexHtml to Invoke-RetryWebRequest and fixed retry logic
- Used Invoke-RetryWebRequest for swagger page as well as index page
> Import-ApimSwaggerApiDefinition retry of web request fix

- azure-pipelines.yml
This is to push the directory as an asset so script can use PSScriptRoot paths
> Add Set-Approleassignments directory as an asset

- Infrastructure-Scripts/Set-AppRoleAssignments/tools/Helpers.psm1
- Create new app registrations with signInAudience of AzureADMyOrg
- Set requestedAccessTokenVersion to 1 so aud of JWT is Identifier URI
https://docs.microsoft.com/en-us/azure/active-directory/develop/access-tokens#payload-claims
> New app registrations to use v1.0 tokens

- Infrastructure-Scripts/New-ConfigurationTableEntry/tools/Helpers.psm1
- Infrastructure-Scripts/New-ConfigurationTableEntry/tools/packages.config
Newtonsoft.Json: From version 9.0.1 targetFramework netstandard1.0 to version 13.0.1 targetFramework netstandard2.0
Newtonsoft.Json.Schema: From version 2.0.8 targetFramework netstandard1.3 to version 3.0.14 targetFramework netstandard2.0
> New-ConfigurationTableEntry: Updated Newtonsoft.Json to 13.0.1 and Newtonsoft.Json.Schema to 3.0.14

- Infrastructure-Scripts/Import-ApimSwaggerApiDefinition.ps1
- Tests/UT.Invoke-CdnContentPurge.Tests.ps1
Added additional header X-Forwarded-Authorization
> Updated Import-APIMSwaggerApiDefinition script

- Infrastructure-Scripts/Add-SearchServiceIpException.ps1
- Tests/UT.Add-SearchServiceIpException.Tests.ps1
Successful pipeline run can be found here:
https://sfa-gov-uk.visualstudio.com/Digital%20Apprenticeship%20Service/_build/results?buildId=846004&view=logs&j=fc42bba5-3572-5309-2a7f-d84dd59586ec&t=3e0a5970-0414-5503-8c38-356103e5e5b7
> added script to add IP whitelist to search service

- Infrastructure-Scripts/Approve-SqlDacpacDeploymentDataLoss.ps1
- Tests/UT.Approve-SqlDacpacDeploymentDataLoss.Tests.ps1
ApproveMOOverrideBlockOnPossibleDataLoss var and condition added for MO environment Dataloss approvals
> ApproveMOOverrideBlockOnPossibleDataLoss var and condition added for MO environment Dataloss approvals

- Infrastructure-Scripts/Get-ProductApplicationInsights.ps1
- Tests/UT.Get-ProductApplicationInsights.Tests.ps1
Added script to return information used to return information of the service's product application insights, used to apply alerts to application insights.
> added Get-ProductApplicationInsights script

- Infrastructure-Scripts/Import-ApimSwaggerApiDefinition.ps1
Added option to add the checkClient Cert policy fragment to the apim api's policy
> added checkClientCert policy fragment to apim api policy

- Infrastructure-Scripts/Import-ApimSwaggerApiDefinition.ps1
Updated APIM policy logic to include checkClientCert fragment if enabled on outer API
> DASD-12694 - updated apim policy and changed set type to rawxml
